export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";
export const SAVE_LAT="SAVE_LAT";
export const SAVE_LONG="SAVE_LONG";